
const qs=id=>document.getElementById(id), KEY='awc_v20_', mails=[{name:'Warehouse H',email:'warehouseh@amsterdamwarehouse.com'},{name:'Willem',email:'willem@amsterdamwarehouse.com'},{name:'Christiaan',email:'christiaan@amsterdamwarehouse.com'},{name:'Warehouse',email:'warehouse@amsterdamwarehouse.com'},{name:'Jacco',email:'jacco@amsterdamwarehouse.com'},{name:'Bas',email:'Bas@amsterdamwarehouse.com'},{name:'Edo',email:'Edo@amsterdamwarehouse.com'},{name:'Daan',email:'Daan@amsterdamwarehouse.com'},{name:'Mira',email:'mira@amsterdamwarehouse.com'},{name:'Order',email:'order@amsterdamwarehouse.com'}];let lang='nl', deferredPrompt=null, photos={p:[],m:[],i:[]};
const tabs=[['dashboard','📊 Dashboard','Overzicht, trends en export'],['pallets','📦 Pallets','Pallettelling met foto en PDF'],['personnel','👥 Personeel','Aanwezigheid per medewerker'],['warehouse','🏭 Warehouse','Ruimtecheck hal, expeditie, terrein en meer'],['orders','⚖️ Order wegen','Gewicht, colli, pallets, afmetingen en artikelen'],['machines','🛠 Machines','Slimme machinekeuring'],['incidents','⚠️ Incidenten','Incident / bijna ongeval'],['damage','💥 Schade','Schade registratie'],['manco','📉 Manco','Manco registratie'],['manual','📖 Handleiding','Gebruiksaanwijzing Nederlands / Engels']];
const critical=['Remmen werken goed','Stuurinrichting werkt goed','Hefmast/vorken veilig','Hydrauliek geen lekkage','Noodstop/veiligheid werkt','Buitenterrein: geen direct gevaar'];
const checkItems=['Algemene staat schoon en veilig','Accu/batterij in goede staat','Geen vloeistoflekkage','Wielen/banden in goede staat','Remmen werken goed','Stuurinrichting werkt goed','Hefmast/vorken veilig','Hydrauliek geen lekkage','Claxon werkt','Verlichting/signalen werken','Noodstop/veiligheid werkt','Stoel/bediening in goede staat','Buitenterrein: geen direct gevaar','Geen losse of uitstekende delen','Ladingdrager/palletvork geen schade'];let checks={};
const PERSON_KEY=KEY+'personList';
const tabLabelsEN={'📊 Dashboard':'📊 Dashboard','📦 Pallets':'📦 Pallets','👥 Personeel':'👥 Staff','🏭 Warehouse':'🏭 Warehouse','⚖️ Order wegen':'⚖️ Order weighing','🛠 Machines':'🛠 Machines','⚠️ Incidenten':'⚠️ Incidents','💥 Schade':'💥 Damage','📉 Manco':'📉 Shortage','📖 Handleiding':'📖 User guide'};
const tabSubsEN={'Overzicht, trends en export':'Overview, trends and export','Pallettelling met foto en PDF':'Pallet count with photo and PDF','Aanwezigheid per medewerker':'Attendance per employee','Ruimtecheck hal, expeditie, terrein en meer':'Area check for hall, expedition, outside and more','Gewicht, colli, pallets, afmetingen en artikelen':'Weight, packages, pallets, dimensions and items','Slimme machinekeuring':'Smart machine inspection','Incident / bijna ongeval':'Incident / near miss','Schade registratie':'Damage registration','Manco registratie':'Shortage registration','Gebruiksaanwijzing Nederlands / Engels':'User guide Dutch / English'};
function initNavLabels(){qs('nav').innerHTML=tabs.map(x=>`<button id="nav_${x[0]}" onclick="show('${x[0]}')">${lang==='en'?(tabLabelsEN[x[1]]||x[1]):x[1]}</button>`).join('')}
function applyI18n(){document.documentElement.lang=lang;qs('mlang').textContent=lang==='nl'?'EN':'NL';document.querySelectorAll('.manual-nl').forEach(e=>e.classList.toggle('hide',lang!=='nl'));document.querySelectorAll('.manual-en').forEach(e=>e.classList.toggle('hide',lang!=='en'));}
function setLang(l){lang=l;localStorage.setItem(KEY+'lang',l);initNavLabels();show(document.querySelector('.tab.active')?.id||'dashboard');}

let persons=JSON.parse(localStorage.getItem(PERSON_KEY)||'[]');
const rooms=['Hal','Expeditie','Buitenterrein','Entresol','Kantine','Kantoor','Technische ruimte','Overige ruimte'];
let selectedRoom='Hal';
const warehouseRoomItems={
  'Hal':['Rijroutes en werkpaden vrij','Vloer schoon, droog en veilig','Stellingen / opslag schadevrij','Goederen stabiel en veilig gestapeld','Geen losliggende folie, hout of afval','Brandblussers en noodmiddelen bereikbaar','Nooduitgangen / vluchtroutes vrij','Verlichting voldoende en werkend','Geen lekkage of gevaarlijke situatie'],
  'Expeditie':['Laad- en loszone vrij en veilig','Dockdeuren / overheaddeuren werken goed','Docklevellers / laadbruggen schadevrij','Geen obstakels bij docks of deuren','Vloer schoon, droog en veilig','Pallets en zendingen staan stabiel opgesteld','Brandblussers en noodmiddelen bereikbaar','Nooduitgangen / vluchtroutes vrij','Verlichting voldoende en werkend','Geen lekkage of gevaarlijke situatie'],
  'Buitenterrein':['Terrein vrij van zwerfafval en losse materialen','Rijroutes voor vrachtwagens vrij','Geen gevaarlijke kuilen, verzakkingen of gladde plekken','Hekwerk, poorten en terreinbeveiliging in orde','Parkeerplaatsen en laad-/losplekken veilig bruikbaar','Afwatering/putten vrij en niet verstopt','Buitenverlichting werkt voldoende','Geen onbeheerde pallets, afval of obstakels tegen gevel/nooddeur','Nooduitgangen aan buitenzijde vrij bereikbaar','Geen lekkage, morsing of gevaarlijke situatie'],
  'Entresol':['Trap en leuning stevig en schadevrij','Entresolvloer schoon en vrij van losse materialen','Maximale belasting niet overschreden','Opslag staat stabiel en niet te dicht bij rand','Valbeveiliging / hekwerk aanwezig en schadevrij','Geen geblokkeerde toegang of vluchtroute','Verlichting voldoende en werkend','Brandblussers en noodmiddelen bereikbaar','Geen lekkage of gevaarlijke situatie'],
  'Kantine':['Vloer schoon, droog en veilig','Tafels en stoelen heel en netjes','Afvalbakken niet overvol','Koelkast/magnetron/koffiehoek schoon','Geen etensresten of ongedierte-indicatie','EHBO/noodmiddelen bereikbaar indien aanwezig','Elektrische apparaten en kabels veilig','Verlichting voldoende en werkend','Geen lekkage of gevaarlijke situatie'],
  'Kantoor':['Werkplekken netjes en veilig','Vloer vrij van kabels en struikelgevaar','Elektrische apparatuur/kabels veilig','Nooduitgang / looproute vrij','Brandblussers en noodmiddelen bereikbaar','Verlichting en klimaat werkbaar','Geen overvolle afvalbakken of brandgevaar','Geen lekkage of gevaarlijke situatie'],
  'Technische ruimte':['Ruimte alleen toegankelijk voor bevoegd personeel','Vloer vrij van obstakels en afval','Elektrakasten/installaties vrij bereikbaar','Geen opslag voor of tegen installaties','Ventilatie vrij en werkend','Blusmiddelen/noodmiddelen bereikbaar','Waarschuwingsstickers/signalisatie aanwezig','Geen lekkage, brandlucht of gevaarlijke situatie'],
  'Overige ruimte':['Ruimte schoon en veilig','Geen obstakels of losliggende materialen','Vloer/wanden/plafond zonder gevaarlijke schade','Opslag staat stabiel en veilig','Noodmiddelen bereikbaar indien aanwezig','Vluchtroute of toegang vrij','Verlichting voldoende en werkend','Geen lekkage of gevaarlijke situatie']
};
function warehouseItems(){return warehouseRoomItems[selectedRoom]||warehouseRoomItems['Overige ruimte']}
function warehouseCriticalForRoom(){return warehouseItems().filter(x=>['Brandblussers en noodmiddelen bereikbaar','Nooduitgangen / vluchtroutes vrij','Nooduitgangen aan buitenzijde vrij bereikbaar','Geen lekkage of gevaarlijke situatie','Geen lekkage, morsing of gevaarlijke situatie','Geen lekkage, brandlucht of gevaarlijke situatie','Elektrakasten/installaties vrij bereikbaar','Valbeveiliging / hekwerk aanwezig en schadevrij','Maximale belasting niet overschreden','Docklevellers / laadbruggen schadevrij'].includes(x))}
let wchecks={};
function resetWarehouseChecks(){wchecks={};warehouseItems().forEach(c=>wchecks[c]=null)}
function init(){lang=localStorage.getItem(KEY+'lang')||'nl';initNavLabels();mails.forEach(m=>document.querySelectorAll('select[id$="_mail"]').forEach(s=>s.innerHTML+=`<option value="${m.email}">${m.name}</option>`));checkItems.forEach(c=>checks[c]=null);resetWarehouseChecks();renderChecks();renderRooms();renderWarehouseChecks();renderPersonnel();['p','m','i','w'].forEach(prefix=>attachPhotos(prefix));addRow('d');addRow('c');addOrderRow();updateOrderTotals();initSig();setNow();renderAll();document.addEventListener('input',()=>{updatePallet();updateMachineStatus();updateOrderTotals();updateWA()});document.addEventListener('change',()=>{updatePallet();updateMachineStatus();updateOrderTotals();updateWA()});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});} 
function show(id){document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));qs(id).classList.add('active');tabs.forEach(x=>qs('nav_'+x[0])?.classList.toggle('active',x[0]===id));const tab=tabs.find(x=>x[0]===id);qs('pageTitle').textContent=(lang==='en'?(tabLabelsEN[tab[1]]||tab[1]):tab[1]).replace(/^[^ ]+ /,'');qs('pageSub').textContent=lang==='en'?(tabSubsEN[tab[2]]||tab[2]):tab[2];side.classList.remove('open');applyI18n();updateWA()}function installApp(){if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;return}alert('Installeren werkt alleen via HTTPS, bijvoorbeeld GitHub Pages, en wanneer de browser de app als PWA accepteert. Android/Chrome: open de site en kies menu ⋮ > App installeren of Toevoegen aan startscherm. iPhone/Safari: Deel-knop > Zet op beginscherm. Niet via een lokaal bestand openen.')}
function now(){return new Date().toLocaleString('nl-NL')}function setNow(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());qs('i_time').value=d.toISOString().slice(0,16)}function hist(t){return JSON.parse(localStorage.getItem(KEY+t)||'[]')}function saveHist(t,o){const a=hist(t);a.unshift({...o,id:crypto.randomUUID?.()||Date.now(),timestamp:now()});localStorage.setItem(KEY+t,JSON.stringify(a));renderAll()}function msg(id,txt,ok=false){qs(id).innerHTML=txt?`<div class="notice ${ok?'ok':'err'}">${txt}</div>`:''}function val(id){return qs(id).value.trim()}function num(id){return Number(qs(id).value||0)}
function attachPhotos(prefix){qs(prefix+'_photos').addEventListener('change',async e=>{photos[prefix]=[];for(const f of e.target.files){photos[prefix].push(await fileData(f))}qs(prefix+'_prev').innerHTML=photos[prefix].map(src=>`<img src="${src}">`).join('');updateWA()})}function fileData(f){return new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(f)})}
function currentPallet(){return{type:'Pallets',user:val('p_user'),location:val('p_loc'),email:val('p_mail'),euro:num('p_euro'),blok:num('p_blok'),two:num('p_2m'),dpb:num('p_dpb'),total:num('p_euro')+num('p_blok')+num('p_2m')+num('p_dpb'),photos:photos.p}}function updatePallet(){const p=currentPallet();qs('p_sum').innerHTML=[['Euro',p.euro],['Blok',p.blok],['2 meter',p.two],['DPB',p.dpb],['Totaal',p.total],['Foto’s',p.photos.length]].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}function savePallet(){const p=currentPallet();if(!p.user)return msg('palletMsg','Vul gebruiker in.');saveHist('pallets',p);msg('palletMsg','Pallettelling opgeslagen.',true)}function mailPallet(){const p=currentPallet();location.href=`mailto:${p.email}?subject=AWC pallettelling ${p.location}&body=${encodeURIComponent(textPallet(p))}`}
function renderChecks(){qs('checks').innerHTML=checkItems.map(c=>`<div class="row ${critical.includes(c)?'critical':''}" id="r_${safe(c)}"><b>${c}${critical.includes(c)?'<span class="tag">KRITIEK</span>':''}</b><button class="choice y" onclick="setCheck('${c}',true)">JA</button><button class="choice n" onclick="setCheck('${c}',false)">NEE</button></div>`).join('')}function safe(s){return s.replace(/\W/g,'_')}function setCheck(c,v){checks[c]=v;const r=qs('r_'+safe(c));r.querySelector('.y').classList.toggle('active',v===true);r.querySelector('.n').classList.toggle('active',v===false);r.classList.toggle('bad',v===false);updateMachineStatus()}function machineResult(){const values=Object.values(checks), missing=values.filter(v=>v===null).length,bad=Object.entries(checks).filter(([k,v])=>v===false),crit=bad.filter(([k])=>critical.includes(k));let status=missing?'NOG NIET COMPLEET':bad.length?'AANDACHT NODIG':'GOEDGEKEURD';if(crit.length)status='AFGEKEURD';return{missing,bad,crit,status}}function updateMachineStatus(){const r=machineResult(),el=qs('m_status');el.textContent=r.status;el.className='pill '+(r.status==='GOEDGEKEURD'?'approved':r.status==='AFGEKEURD'?'rejected':'warning');qs('m_advice').textContent=r.crit.length?'Machine niet gebruiken. Kritieke fout gemeld.':r.bad.length?'Toelichting en foto verplicht bij fout.':'Alles lijkt in orde zodra alle punten zijn ingevuld.'}function currentMachine(){return{type:'Machine',user:val('m_user'),location:val('m_loc'),email:val('m_mail'),machine:val('m_type'),nr:val('m_nr'),serial:val('m_serial'),notes:val('m_notes'),checks:Object.entries(checks).map(([item,value])=>({item,value,critical:critical.includes(item)})),photos:photos.m,status:machineResult().status,signature:qs('sig').toDataURL('image/png')}}function saveMachine(){const m=currentMachine(),r=machineResult();if(!m.user||!m.nr)return msg('mMsg','Vul gebruiker en machinenummer in.');if(r.missing)return msg('mMsg','Vul alle controlepunten in.');if(r.bad.length&&(!m.notes||!m.photos.length))return msg('mMsg','Bij NEE zijn toelichting én foto verplicht.');saveHist('machines',m);msg('mMsg','Machinecheck opgeslagen.',true)}function mailMachine(){const m=currentMachine();location.href=`mailto:${m.email}?subject=AWC machinecheck ${m.nr} ${m.status}&body=${encodeURIComponent(textMachine(m))}`}
function currentIncident(){return{type:'Incident',user:val('i_user'),location:val('i_loc'),email:val('i_mail'),time:val('i_time'),what:val('i_what'),cause:val('i_cause'),injury:val('i_injury'),danger:val('i_danger'),action:val('i_action'),photos:photos.i}}function saveIncident(){const i=currentIncident();if(!i.user||!i.what)return msg('iMsg','Vul melder en gebeurtenis in.');saveHist('incidents',i);msg('iMsg','Incident opgeslagen.',true)}function mailIncident(){const i=currentIncident();location.href=`mailto:${i.email}?subject=AWC incident ${i.location}&body=${encodeURIComponent(Object.entries(i).filter(([k])=>k!=='email').map(([k,v])=>`${k}: ${v}`).join('\n'))}`}
function addRow(p){const box=qs(p+'_rows'),id=p+'_'+Date.now()+Math.random();box.insertAdjacentHTML('beforeend',`<div class="item" data-row="${p}"><div class="grid g3"><div><label>Artikel</label><input class="art"></div><div><label>Aantal</label><input type="number" min="0" class="qty" value="0"></div><div><label>Locatie</label><input class="loc"></div><div><label>${p==='d'?'Schadetype':'Barcode/status'}</label><input class="kind"></div><div><label>Opmerking</label><input class="rem"></div><div><label>Foto</label><input type="file" accept="image/*" multiple onchange="rowPhoto(this)"></div></div><div class="preview"></div><button class="smallbtn" style="margin-top:8px;background:#dc2626" onclick="this.closest('.item').remove()">Verwijder</button></div>`)}async function rowPhoto(inp){const arr=[];for(const f of inp.files)arr.push(await fileData(f));inp.closest('.item').dataset.photos=JSON.stringify(arr);inp.closest('.item').querySelector('.preview').innerHTML=arr.map(s=>`<img src="${s}">`).join('')}function getRows(p){return[...qs((p==='damage'?'d':'c')+'_rows').querySelectorAll('.item')].map(r=>({article:r.querySelector('.art').value,qty:Number(r.querySelector('.qty').value||0),location:r.querySelector('.loc').value,kind:r.querySelector('.kind').value,remarks:r.querySelector('.rem').value,photos:JSON.parse(r.dataset.photos||'[]')})).filter(r=>r.article||r.qty||r.location||r.kind||r.remarks||r.photos.length)}function saveRows(t){const p=t==='damage'?'d':'c',data={type:t,user:val(p+'_user'),location:val(p+'_loc'),client:val(p+'_client'),rows:getRows(t),total:getRows(t).reduce((a,b)=>a+b.qty,0)};if(!data.user||!data.rows.length)return msg(p==='d'?'dMsg':'cMsg','Vul gebruiker en minimaal één regel in.');saveHist(t,data);msg(p==='d'?'dMsg':'cMsg','Registratie opgeslagen.',true)}

function savePersons(){localStorage.setItem(PERSON_KEY,JSON.stringify(persons))}
const personStatusOptions=[['aanwezig','✅ Aanwezig'],['verlof','🌴 Verlof'],['ziek','🤒 Ziek'],['te laat','⏱ Te laat'],['afwezig','❌ Afwezig']];function personStatusLabel(v){const nl={aanwezig:'✅ Aanwezig',verlof:'🌴 Verlof',ziek:'🤒 Ziek','te laat':'⏱ Te laat',afwezig:'❌ Afwezig'};const en={aanwezig:'✅ Present',verlof:'🌴 Leave',ziek:'🤒 Sick','te laat':'⏱ Late',afwezig:'❌ Absent'};return (lang==='en'?en:nl)[v]||v}
function personCounts(){return{present:persons.filter(p=>p.status==='aanwezig').length,leave:persons.filter(p=>p.status==='verlof').length,sick:persons.filter(p=>p.status==='ziek').length,late:persons.filter(p=>p.status==='te laat').length,absent:persons.filter(p=>p.status==='afwezig').length,total:persons.length}}
function personnelStatus(){const c=personCounts();if(!c.total)return'GEEN TEAM';if(c.sick+c.absent>=2)return'ACTIE VEREIST';if(c.sick||c.absent||c.late||c.leave)return'AANDACHT NODIG';return'GOEDGEKEURD'}
function addPerson(){const input=qs('pers_name'),name=(input.value||'').trim();if(!name)return msg('persMsg','Vul eerst een naam in.');persons.push({name,status:'aanwezig',note:''});input.value='';savePersons();renderPersonnel()}
function removePerson(i){persons.splice(i,1);savePersons();renderPersonnel()}
function setPersonStatus(i,status){persons[i].status=status;savePersons();renderPersonnel();updateWA()}
function updatePersonNote(i,value){persons[i].note=value;savePersons();updateWA()}
function setAllPresent(){persons.forEach(p=>p.status='aanwezig');savePersons();renderPersonnel()}
function resetPersonStatus(){persons.forEach(p=>{p.status='aanwezig';p.note='' });savePersons();renderPersonnel()}
function clearPersonList(){if(!confirm('Alle namen uit de personeelslijst wissen?'))return;persons=[];savePersons();renderPersonnel()}
function renderPersonnel(){const list=qs('pers_list');if(!list)return;const c=personCounts(),st=personnelStatus();qs('pers_counts').innerHTML=[['Aanwezig',c.present],['Verlof',c.leave],['Ziek',c.sick],['Te laat',c.late],['Afwezig',c.absent]].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');const badge=qs('pers_status');badge.textContent=st;badge.className='pill '+(st==='GOEDGEKEURD'?'approved':st==='ACTIE VEREIST'?'rejected':'warning');qs('pers_advice').textContent=st==='GOEDGEKEURD'?'Bezetting compleet.':st==='ACTIE VEREIST'?'Meerdere zieken/afwezigen: actie of vervanging nodig.':st==='GEEN TEAM'?'Voeg medewerkers toe aan de lijst.':'Controleer verlof, ziekmeldingen, te laat en afwezigen.';list.innerHTML=persons.length?persons.map((p,i)=>{const cls=p.status==='ziek'?'sick':p.status==='verlof'?'leave':p.status==='afwezig'?'absent':p.status==='te laat'?'late':'';return `<div class="person-card ${cls}"><div class="person-head"><b>${p.name}</b><button class="smallbtn" style="background:#dc2626" onclick="removePerson(${i})">Verwijderen</button></div><div class="person-select"><div><label>Status</label><select onchange="setPersonStatus(${i},this.value)">${personStatusOptions.map(o=>`<option value="${o[0]}" ${p.status===o[0]?'selected':''}>${personStatusLabel(o[0])}</option>`).join('')}</select></div><div><label>Opmerking / reden</label><input placeholder="Bijv. reden, vervanger of tijd" value="${(p.note||'').replace(/"/g,'&quot;')}" oninput="updatePersonNote(${i},this.value)"></div></div><div class="mini">Status: ${p.status}</div></div>`}).join(''):'<div class="item">Nog geen medewerkers toegevoegd.</div>'}

let rosterFoundNames=[];
function rosterMsg(txt){const el=qs('roster_status');if(el)el.textContent=txt}
function setRosterProgress(pct){const el=qs('roster_progress');if(el)el.style.width=Math.max(0,Math.min(100,pct))+'%'}
async function previewRosterImage(inp){const f=inp.files&&inp.files[0];if(!f)return;const src=await fileData(f);qs('roster_preview').innerHTML=`<img src="${src}" alt="Rooster preview">`;rosterMsg('Foto geladen. Klik op Scan roosterfoto om namen te lezen.');setRosterProgress(0)}
function cleanRosterName(line){
  let x=(line||'').replace(/[|_•·;:]+/g,' ').replace(/\s+/g,' ').trim();
  x=x.replace(/\b(0?[0-9]|1[0-9]|2[0-3])[:.][0-5][0-9]\b/g,'').replace(/\b\d{1,2}[-\/ ]\d{1,2}([-\/ ]\d{2,4})?\b/g,'');
  x=x.replace(/\b(ma|di|wo|do|vr|za|zo|mon|tue|wed|thu|fri|sat|sun|dag|avond|nacht|weekend|pauze|shift|start|eind|totaal|datum|naam|afdeling|warehouse|verlof|ziek|vrij)\b/ig,'');
  x=x.replace(/[^A-Za-zÀ-ÖØ-öø-ÿ' .-]/g,' ').replace(/\s+/g,' ').trim();
  if(x.length<3||x.length>45)return'';
  const words=x.split(' ').filter(Boolean);
  if(words.length>4)return'';
  if(!/[A-Za-zÀ-ÖØ-öø-ÿ]{2}/.test(x))return'';
  return words.map(w=>w.charAt(0).toUpperCase()+w.slice(1).toLowerCase()).join(' ');
}
function extractRosterNames(text){
  const skip=/\b(rooster|planning|datum|shift|start|eind|pauze|afdeling|locatie|warehouse|aanwezig|verlof|ziek|vrij|maandag|dinsdag|woensdag|donderdag|vrijdag|zaterdag|zondag)\b/i;
  const raw=(text||'').split(/\n|\r/).map(r=>r.trim()).filter(Boolean);
  const names=[];
  raw.forEach(line=>{
    if(skip.test(line)&&line.split(/\s+/).length<5)return;
    const parts=line.split(/\s{2,}|\t|,/).map(cleanRosterName).filter(Boolean);
    (parts.length?parts:[cleanRosterName(line)]).forEach(n=>{if(n&&!names.some(x=>x.toLowerCase()===n.toLowerCase()))names.push(n)})
  });
  return names.slice(0,60);
}
function renderRosterNames(){
  const box=qs('roster_names');if(!box)return;
  box.innerHTML=rosterFoundNames.length?rosterFoundNames.map((n,i)=>`<div class="ocr-name-row"><input value="${String(n).replace(/"/g,'&quot;')}" oninput="rosterFoundNames[${i}]=this.value"><button class="smallbtn" style="background:#dc2626" onclick="rosterFoundNames.splice(${i},1);renderRosterNames()">×</button></div>`).join('')+'<button class="smallbtn" onclick="rosterFoundNames.push(\'\');renderRosterNames()">+ Naam toevoegen</button>':'<div class="item">Nog geen namen gevonden. Je kunt na de scan namen handmatig corrigeren.</div>';
}
async function scanRosterPhoto(){
  const inp=qs('roster_photo'),file=inp&&inp.files&&inp.files[0];
  if(!file)return rosterMsg('Upload eerst een roosterfoto of screenshot.');
  if(!window.Tesseract)return rosterMsg('OCR kon niet laden. Controleer internetverbinding en probeer opnieuw.');
  rosterMsg('OCR scant de roosterfoto...');setRosterProgress(5);
  try{
    const res=await Tesseract.recognize(file,'nld+eng',{logger:m=>{if(m.status==='recognizing text')setRosterProgress(Math.round((m.progress||0)*90)+5)}});
    setRosterProgress(100);
    rosterFoundNames=extractRosterNames(res.data.text);
    renderRosterNames();
    rosterMsg(rosterFoundNames.length?`${rosterFoundNames.length} mogelijke naam/namen gevonden. Controleer de lijst en klik op Namen overnemen.`:'Geen duidelijke namen gevonden. Probeer een scherpere/rechtere foto of voeg namen handmatig toe.');
  }catch(e){console.error(e);rosterMsg('Scannen mislukt. Probeer een scherpere foto of gebruik handmatig toevoegen.');setRosterProgress(0)}
}
function applyRosterNames(){
  const names=rosterFoundNames.map(n=>String(n||'').trim()).filter(Boolean);
  if(!names.length)return rosterMsg('Geen namen om over te nemen.');
  let added=0;
  names.forEach(name=>{if(!persons.some(p=>p.name.toLowerCase()===name.toLowerCase())){persons.push({name,status:'aanwezig',note:''});added++}});
  savePersons();renderPersonnel();updateWA();rosterMsg(`${added} nieuwe naam/namen overgenomen naar de personeelslijst.`);
}
function clearRosterScan(){rosterFoundNames=[];if(qs('roster_photo'))qs('roster_photo').value='';if(qs('roster_preview'))qs('roster_preview').innerHTML='';setRosterProgress(0);renderRosterNames();rosterMsg('Scan gewist. Upload eventueel een nieuwe roosterfoto.')}

function currentPersonnel(){return{type:'Personeel',lead:val('pers_lead'),shift:val('pers_shift'),location:val('pers_loc'),email:val('pers_mail'),notes:val('pers_notes'),people:persons.map(p=>({...p})),counts:personCounts(),status:personnelStatus()}}
function savePersonnel(){const p=currentPersonnel();if(!p.lead)return msg('persMsg','Vul teamleider in.');if(!p.people.length)return msg('persMsg','Voeg minimaal één medewerker toe.');saveHist('personnel',p);msg('persMsg','Personeel check opgeslagen.',true)}
function mailPersonnel(){const p=currentPersonnel();location.href=`mailto:${p.email}?subject=AWC personeel check ${p.shift} ${p.status}&body=${encodeURIComponent(textPersonnel(p))}`}
function personIcon(st){return st==='aanwezig'?'✅':st==='verlof'?'🌴':st==='ziek'?'🤒':st==='te laat'?'⏱':'❌'}
function absentPeople(p){return (p.people||[]).filter(x=>x.status&&x.status!=='aanwezig')}
function presentPeople(p){return (p.people||[]).filter(x=>!x.status||x.status==='aanwezig')}
function absentTextBlock(p){const a=absentPeople(p);return a.length?'\n\nAFWEZIG / NIET AANWEZIG:\n'+a.map(x=>personIcon(x.status)+' '+x.name+' - '+personStatusLabel(x.status)+(x.note?' - '+x.note:'')).join('\n'):'\n\nAFWEZIG / NIET AANWEZIG:\nGeen afwezigen gemeld.'}
function presentTextBlock(p){const a=presentPeople(p);return a.length?'\n\nAANWEZIG:\n'+a.map(x=>'✅ '+x.name+(x.note?' - '+x.note:'')).join('\n'):'\n\nAANWEZIG:\nGeen aanwezigen gemeld.'}
function textPersonnel(p){return `👥 AWC Personeel check
Teamleider: ${p.lead}
Shift: ${p.shift}
Locatie: ${p.location}
Status: ${p.status}
Aanwezig: ${p.counts.present}
Verlof: ${p.counts.leave}
Ziek: ${p.counts.sick}
Te laat: ${p.counts.late}
Afwezig: ${p.counts.absent}${presentTextBlock(p)}${absentTextBlock(p)}

Opmerking: ${p.notes||'-'}`}

function renderRooms(){const box=qs('room_buttons');if(!box)return;box.innerHTML=rooms.map(r=>`<button class="roombtn ${r===selectedRoom?'active':''}" onclick="setRoom('${r}')">${r}</button>`).join('');qs('custom_room_wrap').classList.toggle('hide',selectedRoom!=='Overige ruimte');updateWarehouseStatus()}
function setRoom(r){selectedRoom=r;resetWarehouseChecks();renderRooms();renderWarehouseChecks();updateWA()}
function renderWarehouseChecks(){const box=qs('w_checks');if(!box)return;const crit=warehouseCriticalForRoom();box.innerHTML=warehouseItems().map(c=>`<div class="row ${crit.includes(c)?'critical':''}" id="wr_${safe(c)}"><b>${c}${crit.includes(c)?'<span class="tag">KRITIEK</span>':''}</b><button class="choice y" onclick="setWarehouseCheck('${c}',true)">JA</button><button class="choice n" onclick="setWarehouseCheck('${c}',false)">NEE</button></div>`).join('')}
function setWarehouseCheck(c,v){wchecks[c]=v;const r=qs('wr_'+safe(c));r.querySelector('.y').classList.toggle('active',v===true);r.querySelector('.n').classList.toggle('active',v===false);r.classList.toggle('bad',v===false);updateWarehouseStatus()}
function warehouseResult(){const values=Object.values(wchecks),missing=values.filter(v=>v===null).length,bad=Object.entries(wchecks).filter(([k,v])=>v===false),crit=bad.filter(([k])=>warehouseCriticalForRoom().includes(k));let status=missing?'NOG NIET COMPLEET':bad.length?'AANDACHT NODIG':'GOEDGEKEURD';if(crit.length)status='AFGEKEURD';return{missing,bad,crit,status}}
function updateWarehouseStatus(){if(!qs('w_status'))return;const r=warehouseResult(),el=qs('w_status');el.textContent=r.status;el.className='pill '+(r.status==='GOEDGEKEURD'?'approved':r.status==='AFGEKEURD'?'rejected':'warning');qs('w_advice').textContent=r.crit.length?'Ruimte direct veiligstellen. Kritieke fout gemeld.':r.bad.length?'Toelichting en foto verplicht bij fout.':'Alles lijkt in orde zodra alle punten zijn ingevuld.'}
function currentWarehouse(){return{type:'Warehouse ruimtecheck',user:val('w_user'),location:val('w_loc'),email:val('w_mail'),room:selectedRoom==='Overige ruimte'?(val('w_custom_room')||'Overige ruimte'):selectedRoom,notes:val('w_notes'),checks:Object.entries(wchecks).map(([item,value])=>({item,value,critical:warehouseCriticalForRoom().includes(item)})),photos:photos.w,status:warehouseResult().status}}
function saveWarehouse(){const w=currentWarehouse(),r=warehouseResult();if(!w.user)return msg('wMsg','Vul controleur in.');if(selectedRoom==='Overige ruimte'&&!val('w_custom_room'))return msg('wMsg','Vul de naam van de overige ruimte in.');if(r.missing)return msg('wMsg','Vul alle controlepunten in.');if(r.bad.length&&(!w.notes||!w.photos.length))return msg('wMsg','Bij NEE zijn toelichting én foto verplicht.');saveHist('warehouse',w);msg('wMsg','Warehouse ruimtecheck opgeslagen.',true)}
function mailWarehouse(){const w=currentWarehouse();location.href=`mailto:${w.email}?subject=AWC warehouse check ${w.room} ${w.status}&body=${encodeURIComponent(textWarehouse(w))}`}
function textWarehouse(w){return `🏭 AWC Warehouse ruimtecheck\nStatus: ${w.status}\nControleur: ${w.user}\nLocatie: ${w.location}\nRuimte: ${w.room}\n\n${w.checks.map(c=>`${c.value===true?'✅':c.value===false?'❌':'⬜'} ${c.item}`).join('\n')}\n\nToelichting: ${w.notes||'-'}`}

function addOrderRow(){const box=qs('o_rows');if(!box)return;box.insertAdjacentHTML('beforeend',`<div class="item" data-order-row><div class="grid g4"><div><label>Artikelnummer</label><input class="o_art" placeholder="Artikelnummer" oninput="updateOrderTotals()"></div><div><label>Hoeveelheid artikelen</label><input type="number" min="0" class="o_qty" value="0" oninput="updateOrderTotals()"></div><div><label>Aantal colli</label><input type="number" min="0" step="1" class="o_colli" value="0" oninput="syncOrderPackages(this.closest('[data-order-row]'))"></div><div><label>Aantal pallets</label><input type="number" min="0" step="1" class="o_pallets" value="0" oninput="syncOrderPackages(this.closest('[data-order-row]'))"></div><div style="grid-column:1/-1"><label>Opmerking artikelregel</label><input class="o_rem" placeholder="Bijv. afwijking, verpakking, label" oninput="updateOrderTotals()"></div></div><div class="muted" style="margin:10px 0 6px">Vul hieronder per colli/pallet het netto gewicht en de afmetingen in.</div><div class="o_packages"></div><button class="smallbtn" style="margin-top:8px;background:#dc2626" onclick="this.closest('.item').remove();updateOrderTotals()">Verwijder regel</button></div>`);syncOrderPackages(box.lastElementChild);updateOrderTotals()}
function packageArticleHtml(data={}){return `<div class="grid g3 o_pkg_article_row" style="margin-top:8px;align-items:end"><div><label>Artikelnummer</label><input class="o_pkg_art" placeholder="Artikelnummer" value="${data.article||''}" oninput="updateOrderTotals()"></div><div><label>Hoeveelheid</label><input type="number" min="0" step="1" class="o_pkg_qty" value="${data.qty||0}" oninput="updateOrderTotals()"></div><div><button class="smallbtn" style="background:#dc2626;width:100%" onclick="this.closest('.o_pkg_article_row').remove();updateOrderTotals()">Verwijder artikel</button></div></div>`}
function packageHtml(type,index,data={}){const label=type==='colli'?'Colli':'Pallet';const arts=(data.articles&&data.articles.length?data.articles:[{}]).map(packageArticleHtml).join('');return `<div class="item" data-package data-type="${type}" data-index="${index}" style="background:#fff;border-style:dashed"><b>${label} ${index}</b><div class="grid g4" style="margin-top:8px"><div><label>Netto gewicht kg</label><input type="number" min="0" step="0.01" class="o_pkg_weight" value="${data.weight||0}" oninput="updateOrderTotals()"></div><div><label>Lengte cm</label><input type="number" min="0" step="0.1" class="o_pkg_l" value="${data.length||0}" oninput="updateOrderTotals()"></div><div><label>Breedte cm</label><input type="number" min="0" step="0.1" class="o_pkg_w" value="${data.width||0}" oninput="updateOrderTotals()"></div><div><label>Hoogte cm</label><input type="number" min="0" step="0.1" class="o_pkg_h" value="${data.height||0}" oninput="updateOrderTotals()"></div></div><div class="muted" style="margin-top:10px">Artikelen in deze ${label.toLowerCase()}</div><div class="o_pkg_articles">${arts}</div><button class="smallbtn" style="margin-top:8px" onclick="addPackageArticle(this)">+ Artikel toevoegen aan ${label.toLowerCase()}</button></div>`}
function addPackageArticle(btn){const box=btn.closest('[data-package]').querySelector('.o_pkg_articles');box.insertAdjacentHTML('beforeend',packageArticleHtml({}));updateOrderTotals()}
function readPackages(row){return[...row.querySelectorAll('[data-package]')].map(p=>{const l=Number(p.querySelector('.o_pkg_l')?.value||0),w=Number(p.querySelector('.o_pkg_w')?.value||0),h=Number(p.querySelector('.o_pkg_h')?.value||0);const articles=[...p.querySelectorAll('.o_pkg_article_row')].map(a=>({article:a.querySelector('.o_pkg_art')?.value.trim()||'',qty:Number(a.querySelector('.o_pkg_qty')?.value||0)})).filter(a=>a.article||a.qty);return{type:p.dataset.type,index:Number(p.dataset.index||0),weight:Number(p.querySelector('.o_pkg_weight')?.value||0),length:l,width:w,height:h,volume_m3:Math.round((l*w*h/1000000)*1000)/1000,articles}})}
function syncOrderPackages(row){if(!row)return;const existing={};readPackages(row).forEach(p=>existing[`${p.type}-${p.index}`]=p);const colli=Math.max(0,Math.floor(Number(row.querySelector('.o_colli')?.value||0))),pallets=Math.max(0,Math.floor(Number(row.querySelector('.o_pallets')?.value||0)));row.querySelector('.o_colli').value=colli;row.querySelector('.o_pallets').value=pallets;let html='';for(let i=1;i<=colli;i++)html+=packageHtml('colli',i,existing[`colli-${i}`]);for(let i=1;i<=pallets;i++)html+=packageHtml('pallet',i,existing[`pallet-${i}`]);row.querySelector('.o_packages').innerHTML=html||'<div class="muted">Vul eerst aantal colli of pallets in.</div>';updateOrderTotals()}
function orderRows(){return[...qs('o_rows').querySelectorAll('[data-order-row]')].map(r=>{const packages=readPackages(r),colli=Number(r.querySelector('.o_colli').value||0),pallets=Number(r.querySelector('.o_pallets').value||0),weight=Math.round(packages.reduce((a,b)=>a+b.weight,0)*100)/100,volume_m3=Math.round(packages.reduce((a,b)=>a+b.volume_m3,0)*1000)/1000,articleQty=packages.reduce((a,p)=>a+(p.articles||[]).reduce((x,y)=>x+y.qty,0),0);return{article:r.querySelector('.o_art').value.trim(),qty:articleQty||Number(r.querySelector('.o_qty').value||0),colli,pallets,weight,volume_m3,packages,remarks:r.querySelector('.o_rem').value.trim()}}).filter(r=>r.article||r.qty||r.colli||r.pallets||r.weight||r.volume_m3||r.remarks||r.packages.some(p=>(p.articles||[]).length))}
function orderTotals(rows=orderRows()){return{qty:rows.reduce((a,b)=>a+b.qty,0),colli:rows.reduce((a,b)=>a+b.colli,0),pallets:rows.reduce((a,b)=>a+b.pallets,0),weight:Math.round(rows.reduce((a,b)=>a+b.weight,0)*100)/100,volume:Math.round(rows.reduce((a,b)=>a+b.volume_m3,0)*1000)/1000,lines:rows.length}}
function updateOrderTotals(){if(!qs('o_totals'))return;const t=orderTotals();qs('o_totals').innerHTML=[['Regels',t.lines],['Hoeveelheid',t.qty],['Colli',t.colli],['Pallets',t.pallets],['Netto gewicht kg',t.weight],['Volume m³',t.volume]].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
function currentOrder(){const rows=orderRows();return{type:'Order wegen',user:val('o_user'),location:val('o_loc'),email:val('o_mail'),order:val('o_order'),client:val('o_client'),notes:val('o_notes'),rows,totals:orderTotals(rows)}}
function saveOrder(){const o=currentOrder();if(!o.user||!o.order)return msg('oMsg','Vul gebruiker en ordernummer in.');if(!o.rows.length)return msg('oMsg','Voeg minimaal één orderregel toe.');saveHist('orders',o);msg('oMsg','Orderweging opgeslagen.',true)}
function mailOrder(){const o=currentOrder();location.href=`mailto:${o.email}?subject=AWC orderweging ${o.order}&body=${encodeURIComponent(textOrder(o))}`}
function packageText(p){const label=p.type==='colli'?'Colli':'Pallet';const arts=(p.articles||[]).map(a=>`    • Artikel ${a.article||'-'} | aantal ${a.qty}`).join('\n');return `  - ${label} ${p.index}: ${p.weight} kg netto | ${p.length}x${p.width}x${p.height} cm | ${p.volume_m3} m³${arts?'\n'+arts:''}`}
function textOrder(o){return `⚖️ AWC Orderweging
Gebruiker: ${o.user}
Locatie: ${o.location}
Order: ${o.order}
Klant/leverancier: ${o.client||'-'}
Regels: ${o.totals.lines}
Hoeveelheid: ${o.totals.qty}
Colli: ${o.totals.colli}
Pallets: ${o.totals.pallets}
Netto gewicht: ${o.totals.weight} kg
Volume: ${o.totals.volume} m³

${o.rows.map(r=>`Artikel ${r.article||'-'} | aantal ${r.qty} | colli ${r.colli} | pallets ${r.pallets} | netto ${r.weight} kg | volume ${r.volume_m3} m³${r.remarks?' | '+r.remarks:''}\n${(r.packages||[]).map(packageText).join('\n')}`).join('\n\n')}

Opmerking: ${o.notes||'-'}`}


function currentRowsData(t){const p=t==='damage'?'d':'c';const rows=getRows(t);return{type:t,user:val(p+'_user'),location:val(p+'_loc'),email:val(p+'_mail'),client:val(p+'_client'),rows,total:rows.reduce((a,b)=>a+b.qty,0),photoCount:rows.reduce((a,b)=>a+(b.photos?.length||0),0)}}
function textRows(t,data=currentRowsData(t)){const title=t==='damage'?'💥 AWC Schade registratie':'📉 AWC Manco registratie';const soort=t==='damage'?'Schadetype':'Barcode/status';const regels=data.rows.length?data.rows.map((r,i)=>`${i+1}. Artikel: ${r.article||'-'} | Aantal: ${r.qty||0} | Locatie: ${r.location||'-'} | ${soort}: ${r.kind||'-'} | Opmerking: ${r.remarks||'-'} | Foto’s: ${(r.photos||[]).length}`).join('\n'):'Geen regels ingevuld';return `${title}\nGebruiker: ${data.user||'-'}\nVestiging: ${data.location||'-'}\nKlant/leverancier: ${data.client||'-'}\nTotaal stuks: ${data.total||0}\nAantal foto's: ${data.photoCount||0}\n\nRegels:\n${regels}\n\nLet op: de mail bevat de tekstgegevens. Voeg de PDF/foto’s handmatig toe als bijlage wanneer nodig.`}
function mailRows(t){const data=currentRowsData(t);if(!data.user||!data.rows.length)return msg(t==='damage'?'dMsg':'cMsg','Vul gebruiker en minimaal één regel in voordat je mailt.');const onderwerp=t==='damage'?`AWC schade registratie ${data.location}`:`AWC manco registratie ${data.location}`;location.href=`mailto:${data.email}?subject=${encodeURIComponent(onderwerp)}&body=${encodeURIComponent(textRows(t,data))}`}
function renderAll(){renderStats();renderHistory('pallets','p_hist');renderHistory('personnel','pers_hist');renderHistory('warehouse','w_hist');renderHistory('orders','o_hist');renderHistory('machines','m_hist');renderHistory('incidents','i_hist');renderHistory('damage','d_hist');renderHistory('manco','c_hist');updatePallet();updateMachineStatus();updateWarehouseStatus();renderPersonnel();updateOrderTotals();updateWA()}
function renderStats(){const ps=hist('pallets'),per=hist('personnel'),ws=hist('warehouse'),os=hist('orders'),ms=hist('machines'),is=hist('incidents'),ds=hist('damage'),cs=hist('manco');const totalP=ps.reduce((a,b)=>a+(b.total||0),0),faults=ms.filter(m=>m.status!=='GOEDGEKEURD').length+ws.filter(w=>w.status!=='GOEDGEKEURD').length;qs('stats').innerHTML=[['Palletchecks',ps.length],['Personeel checks',per.length],['Warehouse checks',ws.length],['Orderwegingen',os.length],['Machinechecks',ms.length],['Afgekeurd/aandacht',faults],['Incidenten',is.length],['Schades',ds.length],['Manco',cs.length],['Totaal pallets',totalP],['Laatste update',[...ps,...per,...ws,...os,...ms,...is,...ds,...cs][0]?.timestamp||'-']].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');const all=[...ps.map(x=>['Pallets',x]),...per.map(x=>['Personeel',x]),...ws.map(x=>['Warehouse',x]),...os.map(x=>['Order',x]),...ms.map(x=>['Machines',x]),...is.map(x=>['Incident',x]),...ds.map(x=>['Schade',x]),...cs.map(x=>['Manco',x])].slice(0,8);qs('recent').innerHTML=all.length?all.map(([t,x])=>`<div class="item"><b>${t}</b><div>${x.user||x.lead||x.location||'-'} • ${x.timestamp||''}</div><div class="muted">${x.status||x.room||x.location||''}</div></div>`).join(''):'<div class="item">Nog geen registraties.</div>';qs('loctable').innerHTML=['Conakryweg','Slego','Buitenterrein'].map(l=>`<tr><td>${l}</td><td>${ps.filter(x=>x.location===l).length}</td><td>${ms.filter(x=>x.location===l).length}</td><td>${is.filter(x=>x.location===l).length}</td><td>${ds.filter(x=>x.location===l).length}</td><td>${cs.filter(x=>x.location===l).length}</td></tr>`).join('')}function renderHistory(t,id){const a=hist(t);qs(id).innerHTML=a.length?a.map(x=>`<div class="item"><div class="itemtop"><div><b>${x.type||t} - ${x.user||'-'}</b><div class="muted">${x.timestamp} • ${x.location||''} ${x.status?'• '+x.status:''}</div></div><button class="smallbtn" onclick="pdfAny('${t}','${x.id}')">PDF</button></div></div>`).join(''):'<div class="item">Nog geen historie.</div>'}
function doc(title){const {jsPDF}=window.jspdf;const d=new jsPDF('p','mm','a4');d.setFillColor(17,17,17);d.rect(0,0,210,28,'F');d.setTextColor(255,122,0);d.setFontSize(18);d.text('AWC Warehouse Tool',12,18);d.setTextColor(255);d.setFontSize(10);d.text('Amsterdam Warehouse Company • Conakryweg / Slego',118,12);d.text(new Date().toLocaleString('nl-NL'),118,18);d.setTextColor(17);d.setFontSize(16);d.text(title,12,42);return d}function addLines(d,lines,y=52){d.setFontSize(10);lines.forEach(line=>{if(y>275){d.addPage();y=18}d.text(String(line),12,y);y+=7});return y}async function addImgs(d,imgs,y){for(const im of imgs||[]){if(y>220){d.addPage();y=18}try{d.addImage(im,'JPEG',12,y,52,38);y+=44}catch(e){}}return y}async function pdfPallet(p){let d=doc('Pallettelling');let y=addLines(d,[`Gebruiker: ${p.user}`,`Locatie: ${p.location}`,`Euro: ${p.euro}`,`Blok: ${p.blok}`,`2 meter: ${p.two}`,`DPB: ${p.dpb}`,`Totaal: ${p.total}`]);y=await addImgs(d,p.photos,y);d.save(`AWC-pallettelling-${Date.now()}.pdf`)}async function pdfMachine(m){let d=doc(`Machinecheck - ${m.status}`);let y=addLines(d,[`Gebruiker: ${m.user}`,`Locatie: ${m.location}`,`Machine: ${m.machine}`,`Nummer: ${m.nr}`,`Serienummer: ${m.serial}`,`Status: ${m.status}`,`Toelichting: ${m.notes||'-'}`]);m.checks.forEach(c=>{y=addLines(d,[`${c.value===true?'JA':c.value===false?'NEE':'-'} - ${c.item}${c.critical?' (KRITIEK)':''}`],y)});y=await addImgs(d,m.photos,y);try{d.addImage(m.signature,'PNG',120,230,60,25)}catch(e){}d.save(`AWC-machinecheck-${m.nr||Date.now()}.pdf`)}async function pdfPersonnel(p){let d=doc(`Personeel check - ${p.status}`);let y=addLines(d,[`Teamleider: ${p.lead}`,`Shift: ${p.shift}`,`Locatie: ${p.location}`,`Status: ${p.status}`,`Aanwezig: ${p.counts.present}`,`Verlof: ${p.counts.leave||0}`,`Ziek: ${p.counts.sick||0}`,`Te laat: ${p.counts.late}`,`Afwezig: ${p.counts.absent}`,`Opmerking: ${p.notes||'-'}`]);const present=presentPeople(p),absent=absentPeople(p);y=addLines(d,['','AANWEZIG:'],y);if(present.length){present.forEach(x=>{y=addLines(d,[`${x.name}${x.note?' - '+x.note:''}`],y)})}else{y=addLines(d,['Geen aanwezigen gemeld.'],y)}y=addLines(d,['','AFWEZIG / NIET AANWEZIG:'],y);if(absent.length){absent.forEach(x=>{y=addLines(d,[`${x.name} - ${personStatusLabel(x.status)}${x.note?' - '+x.note:''}`],y)})}else{y=addLines(d,['Geen afwezigen gemeld.'],y)}d.save(`AWC-personeel-${Date.now()}.pdf`)}
async function pdfOrder(o){let d=doc(`Orderweging - ${o.order||''}`);let y=addLines(d,[`Gebruiker: ${o.user}`,`Locatie: ${o.location}`,`Ordernummer: ${o.order}`,`Klant/leverancier: ${o.client||'-'}`,`Regels: ${o.totals.lines}`,`Hoeveelheid: ${o.totals.qty}`,`Colli: ${o.totals.colli}`,`Pallets: ${o.totals.pallets}`,`Netto gewicht: ${o.totals.weight} kg`,`Volume: ${o.totals.volume} m3`,`Opmerking: ${o.notes||'-'}`]);y=addLines(d,['','Orderregels:'],y);o.rows.forEach(r=>{y=addLines(d,[`${r.article||'-'} | aantal ${r.qty} | colli ${r.colli} | pallets ${r.pallets} | netto ${r.weight} kg | volume ${r.volume_m3} m3${r.remarks?' | '+r.remarks:''}`],y);(r.packages||[]).forEach(p=>{const label=p.type==='colli'?'Colli':'Pallet';y=addLines(d,[`  - ${label} ${p.index}: ${p.weight} kg netto | ${p.length}x${p.width}x${p.height} cm | ${p.volume_m3} m3`],y);(p.articles||[]).forEach(a=>{y=addLines(d,[`      Artikel ${a.article||'-'} | aantal ${a.qty}`],y)})})});d.save(`AWC-orderweging-${o.order||Date.now()}.pdf`)}

async function pdfWarehouse(w){let d=doc(`Warehouse check - ${w.status}`);let y=addLines(d,[`Controleur: ${w.user}`,`Locatie: ${w.location}`,`Ruimte: ${w.room}`,`Status: ${w.status}`,`Toelichting: ${w.notes||'-'}`]);w.checks.forEach(c=>{y=addLines(d,[`${c.value===true?'JA':c.value===false?'NEE':'-'} - ${c.item}${c.critical?' (KRITIEK)':''}`],y)});y=await addImgs(d,w.photos,y);d.save(`AWC-warehouse-${w.room||Date.now()}.pdf`)}
async function pdfIncident(i){let d=doc('Incidentrapport');let y=addLines(d,[`Melder: ${i.user}`,`Locatie: ${i.location}`,`Tijd: ${i.time}`,`Letsel/schade: ${i.injury}`,`Direct gevaar: ${i.danger}`,`Gebeurtenis: ${i.what}`,`Oorzaak: ${i.cause}`,`Actie/preventie: ${i.action}`]);y=await addImgs(d,i.photos,y);d.save(`AWC-incident-${Date.now()}.pdf`)}async function pdfRows(t){const p=t==='damage'?'d':'c',data={type:t,user:val(p+'_user'),location:val(p+'_loc'),client:val(p+'_client'),rows:getRows(t),total:getRows(t).reduce((a,b)=>a+b.qty,0)};let d=doc(t==='damage'?'Schade registratie':'Manco registratie');let y=addLines(d,[`Gebruiker: ${data.user}`,`Locatie: ${data.location}`,`Klant/leverancier: ${data.client}`,`Totaal stuks: ${data.total}`]);for(const r of data.rows){y=addLines(d,[`${r.article} | aantal ${r.qty} | locatie ${r.location} | ${r.kind} | ${r.remarks}`],y);y=await addImgs(d,r.photos,y)}d.save(`AWC-${t}-${Date.now()}.pdf`)}function pdfAny(t,id){const x=hist(t).find(o=>o.id===id);if(t==='pallets')pdfPallet(x);if(t==='personnel')pdfPersonnel(x);if(t==='warehouse')pdfWarehouse(x);if(t==='orders')pdfOrder(x);if(t==='machines')pdfMachine(x);if(t==='incidents')pdfIncident(x);if(t==='damage'||t==='manco'){let d=doc(t);addLines(d,JSON.stringify(x,null,2).split('\n'));d.save(`AWC-${t}.pdf`)}}
function textPallet(p){return `📦 AWC Pallettelling\nGebruiker: ${p.user}\nLocatie: ${p.location}\nEuro: ${p.euro}\nBlok: ${p.blok}\n2 meter: ${p.two}\nDPB: ${p.dpb}\nTotaal: ${p.total}`}function textMachine(m){return `🛠 AWC Machinecheck\nStatus: ${m.status}\nGebruiker: ${m.user}\nMachine: ${m.machine} ${m.nr}\nLocatie: ${m.location}\n\n${m.checks.map(c=>`${c.value===true?'✅':c.value===false?'❌':'⬜'} ${c.item}`).join('\n')}\n\nToelichting: ${m.notes||'-'}`}function updateWA(){const active=document.querySelector('.tab.active')?.id;let txt='AWC Warehouse Tool';if(active==='pallets')txt=textPallet(currentPallet());if(active==='personnel')txt=textPersonnel(currentPersonnel());if(active==='warehouse')txt=textWarehouse(currentWarehouse());if(active==='orders')txt=textOrder(currentOrder());if(active==='machines')txt=textMachine(currentMachine());if(active==='incidents')txt='⚠️ AWC Incident\n'+val('i_what');if(active==='damage')txt=textRows('damage');if(active==='manco')txt=textRows('manco');qs('wa').href='https://wa.me/?text='+encodeURIComponent(txt+'\n\n'+location.href)}
function excelRows(t){let data=hist(t);if(!data.length&&['damage','manco'].includes(t))data=getRows(t);if(!Array.isArray(data))data=[data];const flat=data.map(o=>{const c={...o};delete c.photos;delete c.signature;delete c.checks;delete c.rows;return c});const ws=XLSX.utils.json_to_sheet(flat),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,t);XLSX.writeFile(wb,`AWC-${t}.xlsx`)}function exportAllExcel(){['pallets','personnel','warehouse','orders','machines','incidents','damage','manco'].forEach(t=>{if(hist(t).length)excelRows(t)})}function backupJSON(){const data={pallets:hist('pallets'),personnel:hist('personnel'),warehouse:hist('warehouse'),orders:hist('orders'),machines:hist('machines'),incidents:hist('incidents'),damage:hist('damage'),manco:hist('manco')};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='AWC-backup.json';a.click()}async function restoreJSON(inp){const text=await inp.files[0].text(),data=JSON.parse(text);Object.entries(data).forEach(([k,v])=>localStorage.setItem(KEY+k,JSON.stringify(v)));renderAll()}function clearAll(){if(confirm('Alles wissen?')){['pallets','personnel','warehouse','orders','machines','incidents','damage','manco'].forEach(k=>localStorage.removeItem(KEY+k));renderAll()}}
function initSig(){const c=qs('sig'),ctx=c.getContext('2d');function resize(){c.width=c.offsetWidth*2;c.height=c.offsetHeight*2;ctx.scale(2,2);ctx.lineWidth=3;ctx.lineCap='round'}resize();let draw=false;function pos(e){const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:p.clientX-r.left,y:p.clientY-r.top}}c.onpointerdown=e=>{draw=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};c.onpointermove=e=>{if(!draw)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke()};c.onpointerup=()=>draw=false}function clearSig(){const c=qs('sig');c.getContext('2d').clearRect(0,0,c.width,c.height)}

/* V23.8 fixes: Excel, PDF layout, bigger photos, damage/manco saved PDF */
function saveRows(t){const p=t==='damage'?'d':'c',rows=getRows(t),data={type:t,user:val(p+'_user'),location:val(p+'_loc'),email:val(p+'_mail'),client:val(p+'_client'),rows,total:rows.reduce((a,b)=>a+b.qty,0),photoCount:rows.reduce((a,b)=>a+(b.photos?.length||0),0)};if(!data.user||!data.rows.length)return msg(p==='d'?'dMsg':'cMsg','Vul gebruiker en minimaal één regel in.');saveHist(t,data);msg(p==='d'?'dMsg':'cMsg','Registratie opgeslagen.',true)}
function addLines(d,lines,y=52){d.setFontSize(10);lines.forEach(line=>{const wrapped=d.splitTextToSize(String(line),180);wrapped.forEach(w=>{if(y>275){d.addPage();y=18}d.text(w,12,y);y+=6});});return y}
async function addImgs(d,imgs,y){for(const im of imgs||[]){try{const props=d.getImageProperties(im);const pageW=210,maxW=150,maxH=105;let w=maxW,h=(props.height*maxW)/props.width;if(h>maxH){h=maxH;w=(props.width*maxH)/props.height}if(y+h>282){d.addPage();y=18}d.setFontSize(9);d.setTextColor(80);d.text('Foto',12,y);y+=4;d.addImage(im,props.fileType||'JPEG',(pageW-w)/2,y,w,h);y+=h+10;d.setTextColor(17)}catch(e){}}return y}
function packageText(p){const label=p.type==='colli'?'Colli':'Pallet';const arts=(p.articles||[]).map(a=>`      Artikel: ${a.article||'-'}\n      Aantal: ${a.qty}`).join('\n');return `${label} ${p.index}\n  Netto gewicht: ${p.weight} kg\n  Lengte: ${p.length} cm\n  Breedte: ${p.width} cm\n  Hoogte: ${p.height} cm\n  Volume: ${p.volume_m3} m³${arts?'\n  Artikelen:\n'+arts:''}`}
function textOrder(o){return `⚖️ AWC Orderweging\n\nGebruiker: ${o.user}\nLocatie: ${o.location}\nOrder: ${o.order}\nKlant/leverancier: ${o.client||'-'}\n\nTOTALEN\nRegels: ${o.totals.lines}\nHoeveelheid: ${o.totals.qty}\nColli: ${o.totals.colli}\nPallets: ${o.totals.pallets}\nNetto gewicht: ${o.totals.weight} kg\nVolume: ${o.totals.volume} m³\n\nORDERREGELS\n${o.rows.map((r,i)=>`Regel ${i+1}\nArtikelregel: ${r.article||'-'}\nAantal: ${r.qty}\nColli: ${r.colli}\nPallets: ${r.pallets}\nNetto gewicht: ${r.weight} kg\nVolume: ${r.volume_m3} m³\nOpmerking: ${r.remarks||'-'}\n${(r.packages||[]).map(packageText).join('\n\n')}`).join('\n\n')}\n\nOpmerking algemeen: ${o.notes||'-'}`}
async function pdfOrder(o){let d=doc(`Orderweging - ${o.order||''}`);let y=addLines(d,[`Gebruiker: ${o.user}`,`Locatie: ${o.location}`,`Ordernummer: ${o.order}`,`Klant/leverancier: ${o.client||'-'}`,'',`Regels: ${o.totals.lines}`,`Hoeveelheid: ${o.totals.qty}`,`Colli: ${o.totals.colli}`,`Pallets: ${o.totals.pallets}`,`Netto gewicht: ${o.totals.weight} kg`,`Volume: ${o.totals.volume} m3`,`Opmerking: ${o.notes||'-'}`]);y=addLines(d,['','Orderregels:'],y);o.rows.forEach((r,i)=>{y=addLines(d,[`Regel ${i+1}`,`Artikelregel: ${r.article||'-'}`,`Aantal: ${r.qty}`,`Colli: ${r.colli}`,`Pallets: ${r.pallets}`,`Netto gewicht: ${r.weight} kg`,`Volume: ${r.volume_m3} m3`,`Opmerking: ${r.remarks||'-'}`],y);(r.packages||[]).forEach(p=>{const label=p.type==='colli'?'Colli':'Pallet';y=addLines(d,[`  ${label} ${p.index}`,`  Netto gewicht: ${p.weight} kg`,`  Lengte: ${p.length} cm`,`  Breedte: ${p.width} cm`,`  Hoogte: ${p.height} cm`,`  Volume: ${p.volume_m3} m3`],y);(p.articles||[]).forEach(a=>{y=addLines(d,[`    Artikel: ${a.article||'-'}`,`    Aantal: ${a.qty}`],y)});y+=2});y+=3});d.save(`AWC-orderweging-${o.order||Date.now()}.pdf`)}
function textRows(t,data=currentRowsData(t)){const title=t==='damage'?'💥 AWC Schade registratie':'📉 AWC Manco registratie';const soort=t==='damage'?'Schadetype':'Barcode/status';const regels=data.rows.length?data.rows.map((r,i)=>`Regel ${i+1}\nArtikel: ${r.article||'-'}\nAantal: ${r.qty||0}\nLocatie: ${r.location||'-'}\n${soort}: ${r.kind||'-'}\nOpmerking: ${r.remarks||'-'}\nFoto’s: ${(r.photos||[]).length}`).join('\n\n'):'Geen regels ingevuld';return `${title}\n\nGebruiker: ${data.user||'-'}\nVestiging: ${data.location||'-'}\nKlant/leverancier: ${data.client||'-'}\nTotaal stuks: ${data.total||0}\nAantal foto's: ${data.photoCount||0}\n\nREGELS\n${regels}\n\nLet op: de mail bevat de tekstgegevens. Voeg de PDF/foto’s handmatig toe als bijlage wanneer nodig.`}
async function pdfRowsData(t,data){const title=t==='damage'?'Schade registratie':'Manco registratie';const soort=t==='damage'?'Schadetype':'Barcode/status';let d=doc(title);let y=addLines(d,[`Gebruiker: ${data.user||'-'}`,`Locatie: ${data.location||'-'}`,`Klant/leverancier: ${data.client||'-'}`,`Totaal stuks: ${data.total||0}`,`Aantal foto's: ${data.photoCount||data.rows.reduce((a,b)=>a+(b.photos?.length||0),0)}`]);y=addLines(d,['','Regels:'],y);for(const [i,r] of data.rows.entries()){y=addLines(d,[`Regel ${i+1}`,`Artikel: ${r.article||'-'}`,`Aantal: ${r.qty||0}`,`Locatie: ${r.location||'-'}`,`${soort}: ${r.kind||'-'}`,`Opmerking: ${r.remarks||'-'}`,`Foto's: ${(r.photos||[]).length}`],y);y=await addImgs(d,r.photos,y);y+=2}d.save(`AWC-${t}-${Date.now()}.pdf`)}
async function pdfRows(t){pdfRowsData(t,currentRowsData(t))}
function pdfAny(t,id){const x=hist(t).find(o=>o.id===id);if(t==='pallets')pdfPallet(x);if(t==='personnel')pdfPersonnel(x);if(t==='warehouse')pdfWarehouse(x);if(t==='orders')pdfOrder(x);if(t==='machines')pdfMachine(x);if(t==='incidents')pdfIncident(x);if(t==='damage'||t==='manco')pdfRowsData(t,x)}
function excelValue(v){return v===undefined||v===null?'':v}
function excelFlatten(t,data){const rows=[];if(t==='orders'){data.forEach(o=>{(o.rows||[]).forEach((r,ri)=>{if((r.packages||[]).length){(r.packages||[]).forEach(pkg=>{if((pkg.articles||[]).length){pkg.articles.forEach(a=>rows.push({Datum:o.timestamp,Type:o.type,Gebruiker:o.user,Locatie:o.location,Order:o.order,Klant:o.client,Regel:ri+1,Artikelregel:r.article,RegelAantal:r.qty,Colli:r.colli,Pallets:r.pallets,Soort:pkg.type,Nummer:pkg.index,NettoGewichtKg:pkg.weight,LengteCm:pkg.length,BreedteCm:pkg.width,HoogteCm:pkg.height,VolumeM3:pkg.volume_m3,Artikelnummer:a.article,ArtikelAantal:a.qty,Opmerking:r.remarks}))}else rows.push({Datum:o.timestamp,Type:o.type,Gebruiker:o.user,Locatie:o.location,Order:o.order,Klant:o.client,Regel:ri+1,Artikelregel:r.article,RegelAantal:r.qty,Colli:r.colli,Pallets:r.pallets,Soort:pkg.type,Nummer:pkg.index,NettoGewichtKg:pkg.weight,LengteCm:pkg.length,BreedteCm:pkg.width,HoogteCm:pkg.height,VolumeM3:pkg.volume_m3,Opmerking:r.remarks})})}else rows.push({Datum:o.timestamp,Type:o.type,Gebruiker:o.user,Locatie:o.location,Order:o.order,Klant:o.client,Regel:ri+1,Artikelregel:r.article,RegelAantal:r.qty,Colli:r.colli,Pallets:r.pallets,NettoGewichtKg:r.weight,VolumeM3:r.volume_m3,Opmerking:r.remarks})})});return rows}if(t==='damage'||t==='manco'){const soort=t==='damage'?'Schadetype':'BarcodeStatus';data.forEach(o=>{const base=o.rows?o:{user:val((t==='damage'?'d':'c')+'_user'),location:val((t==='damage'?'d':'c')+'_loc'),client:val((t==='damage'?'d':'c')+'_client'),rows:data};(base.rows||[]).forEach((r,i)=>{const row={Datum:base.timestamp,Type:t,Gebruiker:base.user,Vestiging:base.location,KlantLeverancier:base.client,Regel:i+1,Artikel:r.article,Aantal:r.qty,Locatie:r.location,Opmerking:r.remarks,FotoAantal:(r.photos||[]).length};row[soort]=r.kind;rows.push(row)})});return rows}if(t==='machines'||t==='warehouse'){data.forEach(o=>{if((o.checks||[]).length){o.checks.forEach(c=>rows.push({Datum:o.timestamp,Type:o.type,Gebruiker:o.user,Locatie:o.location,Status:o.status,Onderdeel:c.item,Antwoord:c.value===true?'JA':c.value===false?'NEE':'',Kritiek:c.critical?'JA':'NEE',Toelichting:o.notes||''}))}else rows.push(o)});return rows}if(t==='personnel'){data.forEach(o=>(o.people||[]).forEach(p=>rows.push({Datum:o.timestamp,Teamleider:o.lead,Shift:o.shift,Locatie:o.location,Status:o.status,Medewerker:p.name,Aanwezigheidsstatus:p.status,Opmerking:p.note||'',AlgemeneOpmerking:o.notes||''})));return rows}return data.map(o=>{const c={...o};delete c.photos;delete c.signature;delete c.checks;delete c.rows;delete c.people;return c})}
function excelRows(t){let data=hist(t);if(!data.length&&['damage','manco'].includes(t))data=[currentRowsData(t)];if(!data.length)return alert('Geen gegevens om naar Excel te exporteren. Sla eerst een registratie op of vul regels in.');const flat=excelFlatten(t,data).map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,excelValue(v)])));if(!flat.length)return alert('Geen regels gevonden voor Excel.');const ws=XLSX.utils.json_to_sheet(flat),wb=XLSX.utils.book_new();ws['!cols']=Object.keys(flat[0]).map(k=>({wch:Math.min(Math.max(k.length+4,14),32)}));XLSX.utils.book_append_sheet(wb,ws,t.substring(0,31));XLSX.writeFile(wb,`AWC-${t}-${new Date().toISOString().slice(0,10)}.xlsx`)}
function exportAllExcel(){const wb=XLSX.utils.book_new();let added=0;['pallets','personnel','warehouse','orders','machines','incidents','damage','manco'].forEach(t=>{const data=hist(t);if(data.length){const flat=excelFlatten(t,data);if(flat.length){const ws=XLSX.utils.json_to_sheet(flat);ws['!cols']=Object.keys(flat[0]).map(k=>({wch:Math.min(Math.max(k.length+4,14),32)}));XLSX.utils.book_append_sheet(wb,ws,t.substring(0,31));added++}}});if(!added)return alert('Er is nog geen historie om te exporteren.');XLSX.writeFile(wb,`AWC-alles-${new Date().toISOString().slice(0,10)}.xlsx`)}

init();
